### PR TITLE
Fix for Geode gen

### LINKED ISSUE #456: Generation problem with Abyssal Bricks
After updating Railcraft to Series 9, vanilla Minecraft has a new biome Deep Ocean. Add a check to prevent the holes in the sea.

### PR DESCRIPTION
**Pull request by liach**
Fixes #456. Not tested in test world.

### CODE REVIEW

**Comment by liach** [comment]
Anyone could help test?

**Comment by WoodStone** [comment]
It works :D

**Comment by liach** [comment]
Thanks. It prevents geode replacing bottom gravel, and make geodes deeper.

**Comment by CovertJaguar** [comment]
Looks good, I'll make sure it gets in to 9.6 but I want to test it first (I've been kind of busy this last week)

**Comment by liach** [comment]
Thanks. And four days later it will be the fourth year that CoverJaguar has joined github.

**Pull request merged**
