### PR TITLE
- added community anchor

### PR DESCRIPTION
**Pull request by Terpo**
Added a new anchor which will activate if someone is in range. It is only checked if there are player online, so it may happens that other chunkloader will also activate this one.
The anchor will stay active until the next restart occurs. It has no recipe, does not use fuel and can be combined with a sentinel.

### CODE REVIEW

**Comment by Terpo** [comment]
It would be too powerful and unbalanced compared to the normal world -and personal anchor. 

Also it should be used by an admin if a base won't unload correctly any more.

**Comment by CovertJaguar** [comment]
I'll look at this for 9.6, the final version will probably not be quite the same.

**Comment by Terpo** [comment]
Any idea how you want to change it?

**Comment by wshadow** [comment]
I'm gonna leave a link to the original issue here #489 for future reference.

**Comment by CovertJaguar** [comment]
Well I'd like to add a recipe and possibly change the name, and I haven't even looked at the texture yet.

**Comment by Terpo** [comment]
Oh, ok. 
The texture is the same as the other anchors, but with blue corners.

**Comment by bookerthegeek** [comment]
Village anchor?

**Pull request closed without merging**
