### PR TITLE
Allow limiter track to run locomotives in reverse

### PR DESCRIPTION
**Pull request by cruck1000**
Per the idea of issue/suggestion #621 
Like the title says, this PR adds the ability for the limiter track to set locomotives in reverse.
It passed all my tests, then again, I didn't change much.
The texture is up for interpretation, I considered different colors, but in the end I think something like what I did would be good.
The code was **really** simple, changing 3 numbers and a texture :) (If I did it right)
(You write great code CJ)
Preview: image

Use it or don't, just trying to be helpful with my non-professional programming skills :)

### CODE REVIEW

**Comment by Vexatos** [comment]
I'm not sure if this should be a thing...

**Comment by cruck1000** [comment]
I wasn't quite sure either, I don't think there are an unlimited scale of uses, but for the people that actually want it, the feature could be really useful. It almost just seems like it should exist with the other functions of the limiter track.
Idk thou...

**Comment by liach** [comment]
You might investigate that why dosen't CovertJaguar add this mode at first... Somewhat I feel something bad.

**Comment by Forecaster** [comment]
I'm not really opposed. It's use it pretty much limited to allowing trains to automatically back into depos and the like, saving some tracks at the cost of  a few extra limiter tracks.

**Comment by CovertJaguar** [comment]
I actually had textures for this at one point, but I lost them in the HDD crash. I just never got around to adding the functionality.

**Pull request merged**
