### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by Vexatos**

### CODE REVIEW

**Comment by Yopu** [comment]
What advantage does this provide over the current implementation?

**Comment by CovertJaguar** [comment]
Supposedly it fixed issues with resources when running IntelliJ.

**Comment by Yopu** [comment]
No objections here. Just curious.

**Comment by Vexatos** [comment]
Using IDEA, FML does not recognize resources if they are in a different folder than the java classes. This PR makes IDEA compile both classes and resources into the same folder.

**Pull request merged**
