### PR TITLE
Allow signal capacitors to remain on as long as there is a signal

### PR DESCRIPTION
**Pull request by wshadow**
- fix for CovertJaguar/Railcraft#121
- Capacitor starts countdown when the last input is turned off
- Uses the most restrictive aspect of all active inputs (checked every time the counter would decrement)
- redstone repeater input counts as GREEN aspect

### CODE REVIEW

**Comment by wshadow** [comment]
Keep in mind that his changes the behavior of the signal capacitor and does not add a different box as someone suggested. So this may(?) break existing builds that depend on the old behavior of the capacitor box.

**Comment by CovertJaguar** [comment]
I'd prefer a toggle button in the GUI.

**Comment by wshadow** [comment]
Hm, toggle button. Sounds like a good idea. I'll try to figure out how to design a GUI when I get back home this evening.

**Comment by wshadow** [comment]
Code is finished and works perfectly in my dev env. labels for the new button at CovertJaguar/Railcraft-Localization#278 . I'm not sure if/how the ToolTip works. I included the Strings, but I did not find out how to display them ingame.

**Comment by KamranMackey** [comment]
@wshadow You might want to squash your commits before @CovertJaguar merges it. Just a tip. :)

**Comment by wshadow** [comment]
@KamranMackey huh? Is there a policy for that, that I missed? If not, I'd think it's better not to throw away history?!

**Comment by KamranMackey** [comment]
No, but it is what CovertJaguar suggests when a PR has a lot of commits in it.

**Comment by CovertJaguar** [comment]
Its preferred, otherwise the main history gets cluttered and if I have to revert a PR, its an order of magnitude easier if the PR was a single commit.

**Comment by wshadow** [comment]
Ok, it's your history; give me 10 minutes. Should be easy enough to do.

**Comment by CovertJaguar** [comment]
Thanks!

**Pull request merged**
